# version: '3.3'

# volumes:
#   pg_data:

# services:
#   db:
#     image: postgres:13
#     # env_file: .env
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: Dockerfile
#     volumes:
#       - ../frontend/:/app/result_build/
#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/


# version: '3'

# volumes:
#   pg_data:
#   static:
#   media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
  backend:
    build: ./backend/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static
      - media:/app/media
  frontend:
    env_file: .env
    build: ./frontend/
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    build: ./nginx/
    env_file: .env
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/app/media



# version: '3.3'

# volumes:
#   pg_data:

# services:
#   db:
#     image: postgres:13
#     env_file: .env
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#   backend:
#     build: ./backend/
#     env_file: .env
#     depends_on:
#       - db
#     volumes:
#       - static:/static
#       - media:/app/media
#   frontend:
#     env_file: .env
#     build:
#       context: ../frontend
#       command: cp -r /app/build/. /static/
#       # dockerfile: Dockerfile
#     volumes:
#       - ../frontend/:/app/result_build/
#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../frontend/build:/usr/share/nginx/html/
#       - ../docs/:/usr/share/nginx/html/api/docs/

