version: '3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ugar78/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/static
      - media_volume:/app/media
  frontend:
    image: ugar78/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/app/static
  gateway:
    image: nginx:1.19.3
    env_file: .env
    volumes:
      - static_volume:/static/
      - media_volume:/var/html/media/
    ports:
      - 9000:80
