version: '3.3'

volumes:
  pg_data_production:
  static_volume:
  media_volume:
  data:

services:

  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data/
    restart: always

  backend:
    image: ugar78/foodgram_backend
    env_file: .env
    volumes:
      - data:/app/data/
      - static_volume:/static/
      - media_volume:/app/media/
    depends_on:
      - db
    restart: always

  frontend:
    image: ugar78/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_volume:/static
  gateway:
    image: nginx:1.19.3
    ports:
      - 9000:80
    volumes:

      - static_volume:/var/html/static/
      - media_volume:/var/html/media/

    depends_on:
      - backend
      - frontend
