# Generated by Django 3.2.23 on 2024-02-02 11:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20240202_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления должно быть больше нуля.'), django.core.validators.MaxValueValidator(32000, 'Время приготовления должно быть меньше 32000.')], verbose_name='Время приготовления'),
        ),
    ]
